### ISSUE TITLE
Custom Rules Are Still Kept After Opening Other Saves

### ISSUE THREAD

**Issue by BambooBear0413** [ruzbeh0/SmartTransportation#5]
When opening a save for the first time after launching the game, custom rules are loaded and the default rules are synchronized with the settings as expected.
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/2b316a51-9820-4498-a926-c8b8b1894b73" />

However, when opening another save, or reopening the same save, the previously loaded rules are kept.
As a result, the custom rules list may contain two or more rules that actually represent the same custom rule (if the save is reopened), or multiple identical default rules where one is synchronized with the settings while others are not.
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/875f9439-6d03-4661-9675-ad362e307747" />
(Rules with an “Occupancy Target” of 90% are the unsynchronized default rules.)

**Comment by ruzbeh0** [comment]
The issue has been fixed and the mod updated. Thanks for letting me know

**Comment by BambooBear0413** [comment]
Thanks for the update! I've tested it, but it seems the bug may not be fully fixed.

The rules are no longer duplicated, but the custom rules from the previously loaded save are still kept.

For example, in City A I have a custom rule for interregional buses, and if I start a new save after opening it, the "interregional bus" rule still appears in the custom rules list (which is expected to contain only the default rules).

**Comment by ruzbeh0** [comment]
The mod has been updated and I fixed this issue. Thanks
